import type { Metadata, Viewport } from "next";
import { Space_Grotesk, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Nav";
import { ClockBar } from "@/components/ClockBar";
import { TickerBar } from "@/components/TickerBar";
import { isDemo } from "@/lib/sim/names";

// Space Grotesk for chrome and headings, JetBrains Mono for every figure.
// The mono is the load-bearing choice here: this interface is mostly columns
// of numbers updating in place, and JetBrains Mono's tabular figures and
// unambiguous 0/O and 1/l keep a live table readable at a glance.
const display = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const mono = JetBrains_Mono({
  variable: "--font-mono-ui",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const viewport: Viewport = {
  themeColor: "#161825",
};

export const metadata: Metadata = {
  title: "xcadence — royalty exchange",
  // Names the installed app on a home screen, where the full title is too long.
  applicationName: "xcadence",
  appleWebApp: { capable: true, title: "Xcadence", statusBarStyle: "black-translucent" },
  /**
   * Declared explicitly rather than left to the file conventions, because
   * Safari chooses a tab icon by declared size and ignores sizes it does not
   * expect — the auto-generated link advertised 48x48, which it skipped. PNG at
   * 16 and 32 is what it actually looks for, and mask-icon is what it uses for
   * a pinned tab.
   */
  icons: {
    icon: [
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
    other: [{ rel: "mask-icon", url: "/mask-icon.svg", color: "#8f84d3" }],
  },
  description: "A live simulated exchange in artist royalty shares.",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${mono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-ink">
        <Nav />
        <ClockBar />
        <TickerBar />
        <main className="flex-1">{children}</main>
        <footer className="border-t border-line px-4 py-3 text-xs leading-relaxed text-fg-mute">
          {isDemo() ? (
            <>
              Simulated market. Every artist, price, listener count and royalty
              figure is generated and refers to nobody real.
            </>
          ) : (
            <>
              <span className="text-fg-dim">Simulated market.</span> Artist names,
              photographs, biographies and discographies are real, from Wikipedia
              and MusicBrainz. Everything else — prices, listener counts, royalties,
              growth, volatility, tier and all career events — is generated by a
              seeded random number generator and describes nobody. No affiliation
              with or endorsement by any artist named here is implied.
            </>
          )}{" "}
          Virtual currency sandbox. Not a financial product.
        </footer>
      </body>
    </html>
  );
}
