"use client";

import { Avatar } from "@/components/Avatar";
import { Empty, Panel, TierBadge } from "@/components/ui";
import { EVENT_LABEL } from "@/lib/sim/constants";
import { fmtCompact, fmtInt, fmtListeners, fmtPct } from "@/lib/format";
import { fmtSimDate } from "@/lib/sim/time";

export interface ProfilePayload {
  source: "spotify" | "unavailable" | "simulated";
  isReal: boolean;
  spotifyConfigured: boolean;
  avatar: string | null;
  spotify: {
    id: string; followers: number; popularity: number; genres: string[]; url: string;
  } | null;
  about: {
    genre: string; tier: string; debutMs: number; debutLabel: string; active: boolean;
    exitMs: number | null; exitReason: string | null; monthsListed: number;
    listeners: number; peakListeners: number; peakMonthMs: number;
    bestRank: number | null; volatility: number; monthlyRoyalty: number;
    notable: { tMs: number; kind: string; headline: string }[];
  };
  releases: Release[];
}

type Release =
  | { title: string; type: string; monthKey: number; dateMs: number; listenersAtRelease: number | null; note: string | null }
  | { name: string; type: string; year: number; imageUrl: string | null; url: string; totalTracks: number };

function isSpotifyRelease(r: Release): r is Extract<Release, { name: string }> {
  return "name" in r;
}

export function ArtistHeader({
  name,
  profile,
}: {
  name: string;
  profile: ProfilePayload | null;
}) {
  return <Avatar name={name} src={profile?.avatar} size={64} />;
}

/** About panel: a career summary assembled from the run, not from anywhere else. */
export function AboutPanel({ profile }: { profile: ProfilePayload | null }) {
  if (!profile) return <div className="label px-3 py-8 text-center">Loading profile…</div>;
  const a = profile.about;
  const trajectory =
    a.listeners >= a.peakListeners * 0.95
      ? "at or near their peak"
      : a.listeners >= a.peakListeners * 0.5
        ? `down from a peak of ${fmtListeners(a.peakListeners)}`
        : `well below a peak of ${fmtListeners(a.peakListeners)}`;

  return (
    <Panel title="About" bodyClass="p-4">
      <p className="text-sm leading-relaxed text-fg-dim">
        Listed {a.debutLabel} in <span className="text-fg">{a.genre}</span>, currently classified{" "}
        <TierBadge tier={a.tier} />. {a.monthsListed} months on the exchange,{" "}
        {fmtListeners(a.listeners)} monthly listeners — {trajectory}
        {a.bestRank ? `, with a best rank of #${a.bestRank}` : ""}.{" "}
        {a.active ? (
          <>
            Royalties are running at {fmtCompact(a.monthlyRoyalty)} credits a month against{" "}
            {fmtPct(a.volatility, 0)} annualised volatility.
          </>
        ) : (
          <span className="text-down">
            No longer commercially active as of {a.exitMs ? fmtSimDate(a.exitMs) : "—"}
            {a.exitReason ? ` (${a.exitReason})` : ""}. Contracts pay nothing from that date.
          </span>
        )}
      </p>

      {profile.spotify && (
        <dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-1.5 border-t border-line pt-3 text-xs sm:grid-cols-3">
          <Row k="Spotify followers" v={fmtInt(profile.spotify.followers)} />
          <Row k="Spotify popularity" v={`${profile.spotify.popularity} / 100`} />
          <Row
            k="Spotify genres"
            v={profile.spotify.genres.slice(0, 3).join(", ") || "—"}
          />
        </dl>
      )}

      {a.notable.length > 0 && (
        <div className="mt-4 border-t border-line pt-3">
          <div className="label mb-2">Career events in this run</div>
          <ul className="space-y-1">
            {a.notable.map((e, i) => (
              <li key={i} className="flex items-baseline gap-2 text-xs">
                <span className="num shrink-0 text-fg-mute">{fmtSimDate(e.tMs)}</span>
                <span className="label w-24 shrink-0">{EVENT_LABEL[e.kind] ?? e.kind}</span>
                <span className="truncate text-fg-dim">{e.headline}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {profile.isReal && (
        <p className="mt-4 border-t border-line pt-3 text-xs leading-relaxed text-fg-mute">
          Everything above except the Spotify figures is generated by this simulation and
          describes nobody. Listener counts, royalties, tier, volatility and the career events
          listed are output from a seeded random number generator.
        </p>
      )}
    </Panel>
  );
}

/** Discography. Real releases for real artists, generated ones for the rest. */
export function DiscographyPanel({ profile }: { profile: ProfilePayload | null }) {
  if (!profile) return null;

  if (profile.isReal && profile.source !== "spotify") {
    return (
      <Panel title="Discography" right={<span className="label">real releases only</span>}>
        <div className="px-4 py-8 text-center">
          <p className="text-sm text-fg-dim">
            {profile.spotifyConfigured
              ? "No Spotify match for this name."
              : "Spotify is not connected."}
          </p>
          <p className="mx-auto mt-2 max-w-lg text-xs leading-relaxed text-fg-mute">
            This is a real artist, so their catalogue is not generated — inventing albums for a
            real person would read as a factual claim, which nothing in this simulation is
            entitled to make. Add <span className="num text-fg-dim">SPOTIFY_CLIENT_ID</span> and{" "}
            <span className="num text-fg-dim">SPOTIFY_CLIENT_SECRET</span> to{" "}
            <span className="num text-fg-dim">.env</span> and their real releases will appear here.
          </p>
        </div>
      </Panel>
    );
  }

  const releases = profile.releases ?? [];
  if (releases.length === 0) {
    return (
      <Panel title="Discography">
        <Empty>No releases yet</Empty>
      </Panel>
    );
  }

  return (
    <Panel
      title="Discography"
      right={
        <span className="label">
          {profile.source === "spotify" ? "via Spotify" : "simulated"} · {releases.length}
        </span>
      }
      bodyClass="max-h-[520px] overflow-auto p-3"
    >
      <ul className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
        {releases.map((r, i) => {
          const spotify = isSpotifyRelease(r);
          const title = spotify ? r.name : r.title;
          const year = spotify ? r.year : new Date(r.dateMs).getUTCFullYear();
          const body = (
            <>
              <span
                className="mb-2 block aspect-square w-full overflow-hidden border border-line-2"
                style={{
                  background: spotify && r.imageUrl ? undefined : coverGradient(title),
                }}
              >
                {spotify && r.imageUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={r.imageUrl}
                    alt=""
                    loading="lazy"
                    className="h-full w-full object-cover"
                  />
                ) : null}
              </span>
              <span className="block truncate text-xs text-fg" title={title}>
                {title}
              </span>
              <span className="label mt-0.5 block">
                {r.type} · {year || "—"}
                {spotify && r.totalTracks ? ` · ${r.totalTracks} tracks` : ""}
              </span>
              {!spotify && r.note && (
                <span className="mt-1 block truncate text-[11px] text-accent" title={r.note}>
                  {r.note}
                </span>
              )}
            </>
          );

          return (
            <li key={i}>
              {spotify && r.url ? (
                <a
                  href={r.url}
                  target="_blank"
                  rel="noreferrer noopener"
                  className="block hover:opacity-80"
                >
                  {body}
                </a>
              ) : (
                <span className="block">{body}</span>
              )}
            </li>
          );
        })}
      </ul>
      {profile.source === "simulated" && (
        <p className="mt-3 border-t border-line pt-2 text-xs leading-relaxed text-fg-mute">
          This artist is generated, so the catalogue is too — titles, dates and cadence come from
          the run seed. Where a release lines up with a market event the event is noted beneath
          it, but the engine has no release model: that is presentation, not causation.
        </p>
      )}
    </Panel>
  );
}

/** Deterministic sleeve art for generated releases. */
function coverGradient(title: string): string {
  let h = 0;
  for (let i = 0; i < title.length; i++) h = (h * 31 + title.charCodeAt(i)) >>> 0;
  const a = h % 360;
  const b = (a + 55) % 360;
  return `linear-gradient(145deg, hsl(${a} 34% 26%), hsl(${b} 30% 12%))`;
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex items-baseline justify-between gap-2">
      <dt className="text-fg-mute">{k}</dt>
      <dd className="num text-fg">{v}</dd>
    </div>
  );
}
