import { prisma } from "@/lib/db";
import { RNG } from "@/lib/rng";
import { generateNames, genreFor, GENRES, isDemo, ROSTER, universeSize } from "@/lib/sim/names";
import {
  advanceDays,
  applyMarketShock,
  MARKET_SHOCK_SD,
  monthBoundary,
  monthlyRoyalty,
  targetListeners,
  type ArtistState,
  type SimEvent,
} from "@/lib/sim/dynamics";
import { qForPrice } from "@/lib/sim/lmsr";
import {
  classifyTier,
  CONTRACT_PRICE_BAND,
  STARTING_CREDITS,
  TIER_DEPTH,
  type Tier,
} from "@/lib/sim/constants";
import { dcf, estimateInputs } from "@/lib/quant/dcf";
import { monthKey, monthKeyToMs, MS_DAY } from "@/lib/sim/time";

/** Simulated "today" when a run is created. Fixed so seeds reproduce exactly. */
export const SIM_START_MS = Date.UTC(2026, 8, 1);
export const HISTORY_MONTHS = 36;
/**
 * In real mode the universe is exactly the roster, so the venue is a closed
 * cohort: nothing debuts and exits shrink it. In demo mode names are generated,
 * which restores continuous entry and with it the survival and survivorship
 * tooling's supply of fresh cohorts.
 */
export const UNIVERSE_SIZE = universeSize();
export const BOT_COUNT = 32;

const BOT_STRATEGIES = [
  { strategy: "momentum", label: "MOM", weight: 8 },
  { strategy: "meanreversion", label: "REV", weight: 8 },
  { strategy: "fundamental", label: "FUN", weight: 8 },
  { strategy: "noise", label: "NSE", weight: 8 },
] as const;

const BOT_PREFIX = [
  "Cygnet", "Halberd", "Tessera", "Orbital", "Kestrel", "Basalt", "Novena",
  "Pallas", "Ridgeline", "Aperture", "Kelvin", "Sagitta", "Umbra", "Torrent",
  "Placid", "Verdigris", "Ashgrove", "Lodestar", "Quorum", "Nimbus", "Cadre",
  "Fathom", "Bramble", "Ostrich", "Vellum", "Zephyr", "Larkspur", "Onyx",
  "Palisade", "Tundish", "Wraith", "Yardarm",
];
const BOT_SUFFIX = ["Capital", "Partners", "Advisors", "Desk", "Systematic", "Research"];

/**
 * Build a complete run: hidden parameters, 36 months of backfilled history
 * generated by the *same* process the live engine will run forward, an opening
 * market state, synthetic participants, and the user's account.
 *
 * Exited artists are written with `active = false` and an exit date. They are
 * never deleted — every survivorship figure in the app depends on those rows
 * still being there.
 */
export async function createRun(seed: number): Promise<number> {
  const rng = new RNG(seed);
  const demo = isDemo();
  const names = demo
    ? generateNames(rng.fork("names"), UNIVERSE_SIZE)
    : (ROSTER as readonly string[]);
  const startMonth = monthKey(SIM_START_MS) - HISTORY_MONTHS;

  // ---------------------------------------------------------------- artists
  const states: ArtistState[] = [];
  for (let i = 0; i < UNIVERSE_SIZE; i++) {
    const r = rng.fork("artist", i);

    // Every listing is a charting act, so quality no longer piles up at the
    // bottom the way it did when most of the universe was unknown. Still
    // right-skewed — being signed and being Kendrick are different things.
    const trueQuality = Math.min(0.98, Math.max(0.05, Math.pow(r.next(), 1.6) * 1.05));

    // Roughly a fifth of the old rate. These are established artists, not
    // emerging acts, and the previous calibration would have retired a quarter
    // of the roster before the run even opened.
    const hazardRate = Math.max(
      0.0002,
      0.004 * Math.exp(-3.4 * trueQuality) * r.uniform(0.7, 1.4),
    );
    const driftMu = -0.011 + 0.05 * trueQuality + r.normal(0, 0.006);
    const sigma = 0.055 + 0.2 * (1 - trueQuality) + r.uniform(0, 0.05);
    const breakoutP = 0.0025 + 0.012 * trueQuality;
    const royaltyRate = r.uniform(0.0028, 0.0062);

    const target = targetListeners({ trueQuality });
    const listeners = Math.max(150, target * Math.exp(r.normal(-0.9, 1.0)));

    // Some artists debut inside the history window; the rest predate it.
    const debutMonthsAgo = r.int(2, 140);
    const debutMs = monthKeyToMs(monthKey(SIM_START_MS) - debutMonthsAgo);

    states.push({
      id: i, // temporary; replaced with the DB id after insert
      name: names[i],
      genre: demo ? r.pick(GENRES) : genreFor(names[i]),
      tier: classifyTier(listeners),
      debutTier: classifyTier(listeners),
      debutMs,
      active: true,
      exitMs: null,
      exitReason: null,
      trueQuality,
      hazardRate,
      driftMu,
      sigma,
      breakoutP,
      listeners,
      listeners30: listeners,
      listeners90: listeners,
      volatility: sigma * Math.sqrt(12),
      royaltyRate,
      unitScale: 10_000,
      q: 0,
      b: 1,
      vMax: 1,
      price: 0,
      prevPrice: 0,
      logReturns: [],
      listenerTrail: [listeners],
      dirty: false,
    });
  }

  // ------------------------------------------------- 36 months of history
  type MonthRow = { i: number; monthKey: number; dateMs: number; listeners: number; royalty: number; rank: number };
  const monthRows: MonthRow[] = [];
  const histEvents: (SimEvent & { tMs: number })[] = [];

  for (let m = 0; m < HISTORY_MONTHS; m++) {
    const mk = startMonth + m;
    const tMs = monthKeyToMs(mk);
    const live: { i: number; listeners: number }[] = [];
    // Same common factor the live engine applies, so backfilled history has
    // the same cross-sectional correlation structure as forward-generated data.
    const marketShock = rng.fork("hist-market", mk).normal(0, MARKET_SHOCK_SD);

    for (let i = 0; i < states.length; i++) {
      const a = states[i];
      if (!a.active) continue;
      if (a.debutMs > tMs) continue; // not yet releasing
      const r = rng.fork("hist", i, mk);
      applyMarketShock(a, marketShock);
      advanceDays(a, r, 30);
      for (const e of monthBoundary(a, r, tMs)) histEvents.push({ ...e, tMs });
      live.push({ i, listeners: a.listeners });
    }

    live.sort((x, y) => y.listeners - x.listeners);
    const rankOf = new Map<number, number>();
    live.forEach((e, idx) => rankOf.set(e.i, idx + 1));

    for (const { i } of live) {
      const a = states[i];
      monthRows.push({
        i,
        monthKey: mk,
        dateMs: tMs,
        listeners: a.listeners,
        royalty: monthlyRoyalty(a),
        rank: rankOf.get(i) ?? 0,
      });
    }
  }

  // --------------------------------------------------- opening market state
  for (const a of states) {
    const r = rng.fork("px", a.name);
    const pv = dcf(estimateInputs(a)).pv;

    // Fix the contract unit so this market opens somewhere sensible inside the
    // band. `unitScale` never changes again — every later price move is a real
    // move, not a redenomination.
    // A contract is never more than the whole claim, so artists whose entire
    // royalty stream is worth less than the band floor simply list cheap.
    const openTarget = r.uniform(CONTRACT_PRICE_BAND.lo, CONTRACT_PRICE_BAND.hi);
    a.unitScale = Math.max(1, pv / openTarget);

    // The market does not open at fair value — it opens near it, with error.
    const price = Math.max(0.01, (pv / a.unitScale) * Math.exp(r.normal(0, 0.22)));
    const depth = TIER_DEPTH[a.tier as Tier] ?? TIER_DEPTH.emerging;
    a.b = Math.max(500, depth / price);
    a.vMax = price * 8;
    a.q = qForPrice(price, a.b, a.vMax);
    a.price = price;
    a.prevPrice = price;
  }

  // -------------------------------------------------------------- persist
  const run = await prisma.run.create({
    data: {
      seed,
      simMs: SIM_START_MS,
      startMs: SIM_START_MS,
      speed: 1440,
      running: true,
      tick: 0,
      lastMonthKey: monthKey(SIM_START_MS),
      active: true,
    },
  });

  await prisma.artist.createMany({
    data: states.map((a) => ({
      runId: run.id,
      name: a.name,
      genre: a.genre,
      tier: a.tier,
      debutTier: a.debutTier,
      debutMs: a.debutMs,
      active: a.active,
      exitMs: a.exitMs,
      exitReason: a.exitReason,
      trueQuality: a.trueQuality,
      hazardRate: a.hazardRate,
      driftMu: a.driftMu,
      sigma: a.sigma,
      breakoutP: a.breakoutP,
      listeners: a.listeners,
      listeners30: a.listeners30,
      listeners90: a.listeners90,
      volatility: a.volatility,
      royaltyRate: a.royaltyRate,
      unitScale: a.unitScale,
      q: a.q,
      b: a.b,
      vMax: a.vMax,
      price: a.price,
      prevPrice: a.prevPrice,
    })),
  });

  const created = await prisma.artist.findMany({
    where: { runId: run.id },
    select: { id: true },
    orderBy: { id: "asc" },
  });
  const idOf = (i: number) => created[i].id;
  states.forEach((a, i) => (a.id = idOf(i)));

  await chunked(monthRows, 2000, (batch) =>
    prisma.artistMonth.createMany({
      data: batch.map((r) => ({
        artistId: idOf(r.i),
        monthKey: r.monthKey,
        dateMs: r.dateMs,
        listeners: r.listeners,
        royalty: r.royalty,
        rank: r.rank,
      })),
    }),
  );

  await chunked(histEvents, 2000, (batch) =>
    prisma.marketEvent.createMany({
      data: batch.map((e) => ({
        runId: run.id,
        artistId: e.artistId === null ? null : idOf(e.artistId),
        kind: e.kind,
        magnitude: e.magnitude,
        headline: e.headline,
        tMs: e.tMs,
      })),
    }),
  );

  await prisma.pricePoint.createMany({
    data: states.map((a) => ({ artistId: a.id, tMs: SIM_START_MS, price: a.price })),
  });

  // ------------------------------------------------------------------ bots
  const botRng = rng.fork("bots");
  await prisma.bot.createMany({
    data: Array.from({ length: BOT_COUNT }, (_, i) => {
      const s = BOT_STRATEGIES[i % BOT_STRATEGIES.length];
      const startCash = botRng.uniform(6_000_000, 55_000_000);
      return {
        runId: run.id,
        name: `${BOT_PREFIX[i % BOT_PREFIX.length]} ${botRng.pick(BOT_SUFFIX)}`,
        strategy: s.strategy,
        // Sized to represent the professional side of the venue as a whole,
        // not 32 retail accounts. At ~1M each they collectively could not shift
        // 400 markets whose LMSR depth is 0.4-3M credits apiece, and quotes
        // drifted steadily further from fundamentals instead of converging.
        cash: startCash,
        startCash,
        aggression: botRng.uniform(0.35, 1.4),
        horizon: botRng.int(3, 40),
      };
    }),
  });

  // --------------------------------------------------------------- account
  await prisma.account.create({
    data: {
      runId: run.id,
      cash: STARTING_CREDITS,
      startingCash: STARTING_CREDITS,
      realisedPnl: 0,
      sessionStartEquity: STARTING_CREDITS,
    },
  });

  // -------------------------------------------------------- index baseline
  const activeStates = states.filter((a) => a.active);
  const equalRaw = mean(activeStates.map((a) => a.price));
  const totalListeners = activeStates.reduce((s, a) => s + a.listeners, 0);
  const weightedRaw =
    activeStates.reduce((s, a) => s + a.price * a.listeners, 0) / Math.max(1, totalListeners);

  await prisma.run.update({
    where: { id: run.id },
    data: {
      indexBaseEqual: equalRaw / 100,
      indexBaseWeighted: weightedRaw / 100,
    },
  });
  await prisma.indexPoint.create({
    data: { runId: run.id, tMs: SIM_START_MS, equal: 100, weighted: 100 },
  });
  await prisma.equityPoint.create({
    data: {
      runId: run.id,
      tMs: SIM_START_MS,
      equity: STARTING_CREDITS,
      cash: STARTING_CREDITS,
      marketValue: 0,
      realised: 0,
    },
  });

  // ----------------------------------------------------- opening offerings
  const offerRng = rng.fork("offerings");
  const candidates = states.filter((a) => a.active && (a.tier === "emerging" || a.tier === "dormant"));
  for (let i = 0; i < 9 && candidates.length > 0; i++) {
    const a = candidates[offerRng.int(0, candidates.length - 1)];
    await prisma.offering.create({
      data: buildOffering(a, offerRng, SIM_START_MS, run.id),
    });
  }

  return run.id;
}

/**
 * Price an offering off the *naive* valuation — the one built from the market's
 * tier-based hazard estimate rather than the artist's real hazard. Sellers who
 * know they are worse than they look are therefore systematically happy to sell.
 */
export function buildOffering(
  a: ArtistState,
  rng: RNG,
  tMs: number,
  runId: number,
) {
  const pctRoyalty = rng.uniform(0.02, 0.12);
  const termMonths = rng.pick([36, 60, 84]);
  const est = estimateInputs(a);
  const naive = dcf({
    ...est,
    monthlyRoyalty: est.monthlyRoyalty * pctRoyalty,
    horizonMonths: termMonths,
  }).pv;
  const askCredits = Math.max(250, naive * rng.uniform(0.8, 1.25));
  return {
    runId,
    artistId: a.id,
    pctRoyalty,
    askCredits,
    termMonths,
    openMs: tMs,
    expiresMs: tMs + rng.int(20, 75) * MS_DAY,
    status: "OPEN",
    filled: 0,
  };
}

async function chunked<T>(rows: T[], size: number, fn: (batch: T[]) => Promise<unknown>) {
  for (let i = 0; i < rows.length; i += size) {
    await fn(rows.slice(i, i + size));
  }
}

function mean(xs: number[]): number {
  return xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
}
